config/routes.rb
Hesap::Application.routes.draw do

  devise_for :admins, controllers: { sessions: 'hq/sessions',  registrations: 'hq/registrations', passwords: 'hq/passwords' }, path: 'hq',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification'},
             :skip => [:registrations]
  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', :as => 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', :as => 'admin_registration'
  end

  namespace :hq do
    root to: 'dashboard#index'
    get 'language/:locale' => 'language#change', :as => 'change_language'
    resource :admin_profile, except: [:destroy], path: 'profile'
    resources :users, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
    resources :admins, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
  end

  devise_for :users, controllers: { sessions: 'user/sessions',  registrations: 'user/registrations' }, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification'}

  get 'language/:locale' => 'language#change', :as => 'change_language'
  namespace :user do
    resource :user_profile, except: [:destroy], path: 'profile', as: 'profile'
  end

  root to: 'welcome#index'


end

app/controllers/hq/admin_profiles_controller.rb
# encoding: UTF-8
class Hq::AdminProfilesController < Hq::ApplicationController
  before_action :set_admin_profile, only: [:show, :edit, :update, :destroy]
  add_breadcrumb I18n.t('activerecord.models.admin_profile'), :hq_admin_profile_path

  def show
    add_breadcrumb @admin_profile.first_name, hq_admin_profile_path
    respond_with(:hq, @admin_profile)
  end

  def new
    add_breadcrumb t('tooltips.new'), new_hq_admin_profile_path
    @admin_profile = current_admin.build_admin_profile
    respond_with(:hq, @admin_profile)
  end

  def edit
    add_breadcrumb t('tooltips.edit'), edit_hq_admin_profile_path
  end

  def create
    @admin_profile = current_admin.build_admin_profile(admin_profile_params)
    @admin_profile.save
    respond_with(:hq, @admin_profile, location: hq_admin_profile_path)
  end

  def update
    @admin_profile.update(admin_profile_params)
    respond_with(:hq, @admin_profile, location: hq_admin_profile_path)
  end

  private

  def set_admin_profile
    if current_admin.admin_profile.nil?
      redirect_to new_hq_admin_profile_path
    end
    @admin_profile = current_admin.admin_profile
  end

  def admin_profile_params
    params.require(:admin_profile).permit(:first_name, :gsm, :last_name)
  end
end

app/controllers/hq/admins_controller.rb
class Hq::AdminsController < Hq::ApplicationController

  before_action :set, only: [:block, :unblock]
  add_breadcrumb I18n.t('activerecord.models.admins'), :hq_admins_path

  def index
    @search = Admin.ransack(params[:q])
    @admins = @search.result.paginate(page: params[:page])
  end

  def block_all
    Admin.update_all(blocked: true)
    flash[:success] = t('operation_success')
    redirect_to :back
  end

  def block
    @admin.blocked = true
    if @admin.save
      flash[:success] = t('admins.blocked_success')
    else
      flash[:danger] = t('operation_failed')
    end
    redirect_to :back
  end

  def unblock
    @admin.blocked = false
    if @admin.save
      flash[:success] = t('admins.activated_success')
    else
      flash[:danger] = t('operation_failed')
    end
    redirect_to :back
  end

  private
    def set
      @admin = Admin.find(params[:id])
    end

end

app/controllers/hq/application_controller.rb
require 'application_responder'

class Hq::ApplicationController < ActionController::Base
  before_action :authenticate_admin!
  before_action :set_locale
  self.responder  = ApplicationResponder
  respond_to :html, :json

  private
  def set_locale
    I18n.locale     = current_admin.locale
  end
end

app/controllers/hq/dashboard_controller.rb
class Hq::DashboardController < Hq::ApplicationController

  add_breadcrumb I18n.t('dock.dashboard'), :hq_root_path

  def index
  end

end

app/controllers/hq/language_controller.rb
class Hq::LanguageController < Hq::ApplicationController

  def change
    if params[:locale].in?(['en', 'tr'])
      I18n.locale = params[:locale]
      current_admin.locale = params[:locale]
      current_admin.save
    end
    redirect_to :back
  end

end

app/controllers/hq/passwords_controller.rb
class Hq::PasswordsController < Devise::PasswordsController
  layout 'login'
end

app/controllers/hq/registrations_controller.rb
class Hq::RegistrationsController < Devise::RegistrationsController
  layout 'hq/application'
  before_action :authenticate_admin!
  before_action :redirect_admin, only: [:new, :create, :destroy]
  add_breadcrumb I18n.t('activerecord.models.admin'), :hq_root_path

  def edit
  end

  private

  def redirect_admin
      redirect_to hq_root_path
  end

  def after_update_path_for(resource)
    hq_root_path
  end

end

app/controllers/hq/sessions_controller.rb
class Hq::SessionsController < Devise::SessionsController
  layout 'login'

  private

  # Overwriting the sign_out redirect path method
  def after_sign_in_path_for(resource_or_scope)
    hq_root_path
  end

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end
end

app/controllers/hq/users_controller.rb
class Hq::UsersController < Hq::ApplicationController

  before_action :set_user, only: [:block, :unblock]
  add_breadcrumb I18n.t('activerecord.models.users'), :hq_users_path

  def index
    @search = User.ransack(params[:q])
    @users = @search.result.paginate(page: params[:page])
  end

  def block_all
    User.update_all(blocked: true)
    flash[:success] = t('operation_success')
    redirect_to :back
  end

  def block
    @user.blocked = true
    if @user.save
      flash[:success] = t('users.blocked_success')
    else
      flash[:danger] = t('operation_failed')
    end
    redirect_to :back
  end

  def unblock
    @user.blocked = false
    if @user.save
      flash[:success] = t('users.activated_success')
    else
      flash[:danger] = t('operation_failed')
    end
    redirect_to :back
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/hq/language_helper.rb
module Hq::LanguageHelper
end

app/helpers/hq/registrations_helper.rb
module Hq::RegistrationsHelper
end

app/helpers/hq/users_controller_helper.rb
module Hq::UsersControllerHelper
end

app/views/layouts/hq/partials/_breadcrumb.haml
%ul#breadcrumb.breadcrumb
  = render_breadcrumbs :separator => ' / '

app/views/layouts/hq/partials/_dock.haml
%i#toggle.icon-align-justify.icon-large

%ul#dock
  %li.launcher
    %i.icon-dashboard
    =link_to t('dock.dashboard'), hq_root_path
  %li.launcher
    %i.icon-user
    =link_to t('dock.admins'), hq_admins_path
  %li.launcher
    %i.icon-user
    =link_to t('dock.users'), hq_users_path
  -#%li.launcher
  -#  %i.icon-table
  -#  =link_to 'Tables', '/hq/dashboard/tables.html'
  -#%li.launcher.dropdown.hover
  -#  %i.icon-flag
  -#  %a{href: '#'} Reports
  -#  %ul.dropdown-menu
  -#    %li.dropdown-header Launcher description
  -#    %li
  -#      %a{:href => '#'} Action
  -#    %li
  -#      %a{:href => '#'} Another action
  -#    %li
  -#      %a{:href => '#'} Something else here
  -#%li.launcher
  -#  %i.icon-bookmark
  -#  %a{href: '#'} Bookmarks
  -#%li.launcher
  -#  %i.icon-cloud
  -#  %a{href: '#'} Backup
  -#%li.launcher
  -#  %i.icon-bug
  -#  %a{href: '#'} Feedback

#beaker{data: {toggle: 'tooltip'}, title: 'Made by iso'}

app/views/layouts/hq/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'hq/application', 'data-turbolinks-track' => false
= yield :foot

app/views/layouts/hq/partials/_navbar.haml
#navbar.navbar.navbar-default
  %a.navbar-brand{:href =>  hq_root_url }
    %i.icon-beer
    Hesap
  %ul.nav.navbar-nav.pull-right
    -#%li.dropdown
    -#  %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
    -#    %i.icon-envelope
    -#    Messages
    -#    %span.badge 5
    -#    %b.caret
    -#  %ul.dropdown-menu
    -#    %li
    -#      %a{:href => '#'} New message
    -#    %li
    -#      %a{:href => '#'} Inbox
    -#    %li
    -#      %a{:href => '#'} Out box
    -#    %li
    -#      %a{:href => '#'} Trash
    -#%li
    -#  = link_to  hq_change_language_path('en') do
    -#    %i.icon-cog
    -#    Settings
    %li.dropdown
      %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
        %i.icon-flag
        = t("navbar.language.#{I18n.locale}")
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to  hq_change_language_path('en') do
            %i.icon-flag
            = t('navbar.language.en')
        %li
          = link_to  hq_change_language_path('tr') do
            %i.icon-flag
            = t('navbar.language.tr')
    %li.dropdown.user
      %a.dropdown-toggle{'data-toggle' => 'dropdown', :href => '#'}
        %i.icon-user
        %strong=current_admin.email
        -#=image_tag 'http://lorempixel.com/output/fashion-q-c-20-20-4.jpg', width: '20px', height: '20px', class: 'img-rounded'
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to t('navbar.edit_profile'), edit_hq_admin_profile_path
        %li
          = link_to t('navbar.edit_login_info') , edit_admin_registration_path
        %li.divider
        %li
          =link_to t('navbar.logout') , destroy_admin_session_path, method: :delete

app/views/layouts/hq/partials/_toolbar.haml
#toolbar
  .btn-group
    = yield :toolbar