config/routes.rb
Hesap::Application.routes.draw do

  devise_for :admins, controllers: { sessions: 'hq/sessions',  registrations: 'hq/registrations', passwords: 'hq/passwords' }, path: 'hq',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification'},
             :skip => [:registrations]
  as :admin do
    get 'hq/edit' => 'hq/registrations#edit', :as => 'edit_admin_registration'
    put 'hq' => 'hq/registrations#update', :as => 'admin_registration'
  end

  namespace :hq do
    root to: 'dashboard#index'
    get 'language/:locale' => 'language#change', :as => 'change_language'
    resource :admin_profile, except: [:destroy], path: 'profile'
    resources :users, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
    resources :admins, except: [:create, :new] do
      post :block, on: :member
      post :unblock, on: :member
      post :block_all, on: :collection
    end
  end

  devise_for :users, controllers: { sessions: 'user/sessions',  registrations: 'user/registrations' }, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification'}

  get 'language/:locale' => 'language#change', :as => 'change_language'
  namespace :user do
    resource :user_profile, except: [:destroy], path: 'profile', as: 'profile'
  end

  root to: 'welcome#index'


end

app/views/layouts/partials/_footer.haml
/ Javascripts
= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js',
                         'application', 'data-turbolinks-track' => true

app/views/layouts/partials/_messages.haml
- flash.each do |key, value|
  - if key.to_s == "notice"
    - key = "success"
  - if key.to_s == "alert"
    - key = "danger"
  %div{:class => "alert alert-dismissable alert-#{key}"}
    - if key.to_s == "danger" || key.to_s == "warning"
      %i.fa.fa-exclamation-triangle.fs-25
      %strong
        = t 'errors.message.sory'
        \!
    - else
      %i.fa.fa-smile-o.fs-25{:style => "padding: 0px 5px;"}
    = value

app/views/layouts/partials/_navbar.haml
.masthead
  %ul.nav.nav-pills.pull-right
    - if current_user
      %li.dropdown
        %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
          %i.fa.fa-user
          = current_user.name
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to edit_user_profile_path, class: 'btn btn-large' do
              %i.fa.fa-edit
              = t('navbar.edit_profile')
          %li
            = link_to edit_user_registration_path , class: 'btn btn-large' do
              %i.fa.fa-edit
              = t('navbar.edit_login_info')
          %li.dvider
          %li
            = link_to destroy_user_session_path, class: 'btn btn-large', method: :delete do
              %i.fa.fa-logout
              = t('navbar.logout')
    - else
      %li
        = link_to t('navbar.login'), new_user_session_path
      %li
        = link_to t('navbar.signup'), new_user_registration_path, class: 'btn btn-success'
    %li.dropdown
      %a.dropdown-toggle{data: {toggle: 'dropdown'}, :href => '#'}
        %i.fa.fa-flag
        = t("navbar.language.#{I18n.locale}")
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to change_language_path('en') do
            %i.fa.fa-flag
            = t('navbar.language.en')
        %li
          = link_to change_language_path('tr') do
            %i.fa.fa-flag
            = t('navbar.language.tr')
  %h3.muted= link_to 'Hesap', root_path

app/views/layouts/partials/_trackers.haml
:javascript
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));